---
- name: Monday morning review    # metadata
  connection: local              # use this plugin
  hosts: ansibleController
  gather_facts: false

  tasks:
    # sends an HTTP GET to a target URI
    - name: Http lookup to rzfeeser.com
      ansible.builtin.uri:
        url: https://rzfeeser.com
      register: results

    - name: Display results
      ansible.builtin.debug:
        var: results

    - name: Http lookup to iris7.com
      ansible.builtin.uri:
        url: https://iris7.com
      register: results

    - name: Display results
      ansible.builtin.debug:
        var: results

    - name: Display results
      ansible.builtin.debug:
        msg: "hello zach and students!"
